### PR TITLE
Added support for Indian streaming sites

### PR DESCRIPTION
**Pull request by FireHound-lab**
Like Hotstar, Zee5, Mx player online etc.

### CODE REVIEW

**Comment by Ncode2014** [comment]
@FireHound-lab 😳

**Comment by FireHound-lab** [comment]
Yt-dlp has more supported sites then the official youtube-dl

**Comment by jusidama18** [comment]
https://t.me/SlamMirrorSupport/59456

**Comment by dishapatel010** [comment]
@jusidama18 Use in your custom repo if u want 🧠

**Comment by FireHound-lab** [comment]
Eh, have to resolve some conflicts, closing it

**Pull request closed without merging**
