### PR TITLE
fix typo and add time in count & clone msg

### PR DESCRIPTION
**Pull request by noobzhax**

### CODE REVIEW

**Comment by anasty17** [comment]
Is it important to add time ?

**Comment by xd003** [comment]
Clone progress status would have been really helpful. Time doesn't really help with anything tbh

**Comment by noobzhax** [comment]
> Is it important to add time ?

maybe yes for some people 🤷🏼‍♂️

**Comment by noobzhax** [comment]
> Clone progress status would have been really helpful. Time doesn't really help with anything tbh

ya, it looks more interesting

**Comment by anasty17** [comment]
> > Is it important to add time ?
> 
> maybe yes for some people 🤷🏼‍♂️

To know how much clone took time ! Then he can know from difference of clone msg and result msg time :)

**Comment by anasty17** [comment]
> Clone progress status would have been really helpful. Time doesn't really help with anything tbh

Soon

**Pull request closed without merging**
