### PR TITLE
Updates every restart with git pull

### PR DESCRIPTION
**Pull request by jusidama18**

### CODE REVIEW

**Comment by breakdowns** [comment]
@jusidama18 Need test for this

**Comment by dishapatel010** [comment]
But what about users UPSTREAM REPO?

**Comment by jusidama18** [comment]
> But what about users UPSTREAM REPO?

no need it's updates from your repo

**Comment by anasty17** [comment]
@jusidama18 That's better but this must be optional

**Comment by dishapatel010** [comment]
> > But what about users UPSTREAM REPO?
> 
> no need it's updates from your repo

with out custom UPSTREAM REPO?

**Comment by jusidama18** [comment]
> @jusidama18 That's better but this must be optional

Done now 👍

**Comment by dishapatel010** [comment]
@jusidama18 But gone upstream repo sed!!

**Pull request closed without merging**
