### PR TITLE
ptb: Upgrade

### PR DESCRIPTION
**Pull request by tomyprs**
:-)

Signed-off-by: TomyPrs <tomy.prs25@gmail.com>

### CODE REVIEW

**Review by a092devs — COMMENTED** [review]
add back "drop_pending_updates=IGNORE_PENDING_REQUESTS" in line 235 of bot/__main__.py

**Comment by tomyprs** [comment]
> add back "drop_pending_updates=IGNORE_PENDING_REQUESTS" in line 235 of bot/**main**.py

ah me not using this repo lol

**Comment by tomyprs** [comment]
> Close this pr he miss some edits

nah, that's why oepn source code, if you review my code, and you got some missed, you also can contribute :-)

**Comment by a092devs** [comment]
> > add back "drop_pending_updates=IGNORE_PENDING_REQUESTS" in line 235 of bot/**main**.py
> 
> ah me not using this repo lol

Add in your repo and create PR again.

**Pull request closed without merging**
